FROM ghcr.io/actions/actions-runner:latest
USER root
# Create the certs directory
RUN mkdir -p /etc/docker/certs.d/mihir.harbor.com/

# Copy the Harbor certificate
COPY harbor.crt /etc/docker/certs.d/mihir.harbor.com/ca.crt

# Update CA certificates
RUN cp /etc/docker/certs.d/mihir.harbor.com/ca.crt /usr/local/share/ca-certificates/harbor.crt \
    && update-ca-certificates

USER runner